# Configuración de conexión a la base de datos PostgreSQL en Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/gestordb
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate/JPA
# 'update' creará las tablas si no existen y las actualizará si hay cambios en los modelos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostrar las consultas SQL en la consola (opcional, muy útil para debuggear)
spring.jpa.show-sql=true