spring.application.name=backend
# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestordb
spring.datasource.username=gestor_user
spring.datasource.password=gestor_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
